# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# User specific aliases and functions
export XOA_URL=ws://xoa.dwlabs.fun
export XOA_USER=admin@dwlabs.fun
export XOA_PASSWORD=pfqqzt64
#export ANSIBLE_VAULT_PASSWORD_FILE=~/ansible/passwd.yml
